from turtle import *

tom = Turtle()
window = Screen()
window.tracer(False)
Screen().bgcolor('#6097FE')
tom.speed(0)
window = Screen()
tom.color('orange')
window.setup(width=1.0, height=1.0)

def sun():
    tom.color('#F99B37')
    for i in range(300):

        tom.fd(100)
        tom.bk(100)
        tom.rt(360/300)
    
    tom.color('orange')
    tom.pu()
    tom.goto(659,319)
    tom.pd()
    tom.begin_fill()
    tom.circle(65)
    tom.end_fill()

def lay():
    sq('#466902')
    sq('#9BA90C')
    sq('#9BA90C')
    sq('#466902')
def bl():
    sq('#466902')
    sq('#466902')
    sq('#9BA90C')
    sq('#9BA90C')
    sq('#466902')
    sq('#466902')
def sq(color):
    tom.fillcolor(color)
    tom.begin_fill()
    for _ in range(4):
        tom.forward(30)
        tom.right(90)
    tom.fd(30)
    tom.end_fill()
tom.pu()
tom.goto(-250,-300)
tom.pd()
for i in range(4):
    sq('maroon')
tom.pu()
tom.goto(-220,-270)
tom.pd()
for i in range(3):
    sq('maroon')
tom.pu()
tom.goto(-220+30,-270+30)
tom.pd()
for i in range(3):
    sq('blue')
tom.pu()
tom.goto(-190,-210)
tom.pd()
for i in range(3):
    sq('blue')
tom.pu()
tom.goto(-160,-180)
tom.pd()
for i in range(6):
    sq('blue')
tom.pu()
tom.goto(-100,-210)
tom.pd()
for i in range(5):
    sq('blue')
tom.pu()
tom.goto(-40,-240)
tom.pd()
for i in range(3):
    sq('blue')
tom.pu()
tom.goto(-10.0,-270.0)
tom.pd()
for i in range(3):
    sq('maroon')
tom.pu()
tom.goto(-10.0,-300.0)
tom.pd()
for i in range(4):
    sq('maroon')
tom.pu()
tom.goto(-250.0,-210.0)
tom.pd()
for i in range(2):
    sq('#FECBA0')
tom.pu()
tom.goto(-250.0,-180.0)
tom.pd()
for i in range(3):
    sq('#FECBA0')
tom.pu()
tom.goto(-250.0,-180.0+30)
tom.pd()
for i in range(2):
    sq('#FECBA0')
sq('red')
sq('blue')
sq('yellow')
sq('blue')
sq('blue')
sq('yellow')
sq('blue')
sq('red')
for i in range(2):
    sq('#FECBA0')
tom.pu()
tom.goto(20.0,-180.0)
tom.pd()
for i in range(3):
    sq('#FECBA0')
tom.pu()
tom.goto(20.0,-150.0)
tom.pd()
sq('red')
for i in range(2):
    sq('#FECBA0')
tom.pu()
tom.goto(-250.0,-149.0+30)
tom.pd()
for i in range(4):
    sq('red')
for i in range(4):
    sq('blue')
for i in range(4):
    sq('red')
tom.pu()
tom.goto(-220,-90)
tom.pd()
for i in range(3):
    sq('red')
sq('blue')
sq('red')
sq('red')
sq('blue')
for i in range(3):
    sq('red')
tom.pu()
tom.goto(-190,-90+30)
tom.pd()
for i in range(2):
    sq('red')
sq('blue')
for i in range(4):
    sq('red')
tom.pu()
tom.goto(-160,-30)
tom.pd()
for i in range(8):
    sq('#FECBA0')
tom.pu()
tom.goto(-220,0)
tom.pd()
for i in range(2):
    sq('maroon')
for i in range(5):
    sq('#FECBA0')
for i in range(4):
    sq('black')
tom.pu()
tom.goto(-220,30)
tom.pd()
sq('maroon')
sq('#FECBA0')
for i in range(2):
    sq('maroon')
for i in range(4):
    sq('#FECBA0')
sq('black')
for i in range(3):
    sq('#FECBA0')
tom.pu()
tom.goto(-220,60)
tom.pd()
sq('maroon')
sq('#FECBA0')
sq('maroon')
for i in range(4):
    sq('#FECBA0')
sq('black')
for i in range(3):
    sq('#FECBA0')
tom.pu()
tom.goto(-190,90)
tom.pd()
for i in range(3):
    sq('maroon')
for i in range(3):
    sq('#FECBA0')
sq('black')
sq('#FECBA0')
tom.pu()
tom.goto(-190,120)
tom.pd()
for i in range(10):
    sq('red')
tom.pu()
tom.goto(-160,150)
tom.pd()
for i in range(6):
    sq('red')
tom.pu()
tom.goto(-956,-330)
tom.pd()
for i in range(100):
    sq('#2A883E')
tom.pu()
tom.goto(-956,-360)
tom.pd()
for i in range(100):
    sq('#b14b4b')
tom.pu()
tom.goto(-956,-390)
tom.pd()
for i in range(100):
    sq('#a5644e')
tom.pu()
tom.goto(-956,-420)
tom.pd()
for i in range(100):
    sq('#b14b4b')
tom.pu()
tom.goto(-956,-500)
tom.pd()
for i in range(100):
    sq('#a5644e')
tom.pu()
tom.goto(-956,-530)
tom.pd()
for i in range(100):
    sq('#b14b4b')
tom.pu()
tom.goto(240,-270)
tom.pd()
for i in range(3):
    sq('#FBBB01')
tom.pu()
tom.goto(210,-240)
tom.pd()
for i in range(5):
    sq('#FBBB01')
tom.pu()
tom.goto(210,-210)
tom.pd()
for i in range(5):
    sq('#FBBB01')
tom.pu()
tom.goto(240,-180)
tom.pd()
for i in range(3):
    sq('#FBBB01')
tom.pu()
tom.goto(420,-270)
tom.pd()
for i in range(3):
    sq('#FBBB01')
tom.pu()
tom.goto(390,-210)
tom.pd()
for i in range(5):
    sq('#FBBB01')
tom.pu()
tom.goto(390,-240)
tom.pd()
for i in range(5):
    sq('#FBBB01')
tom.pu()
tom.goto(420,-180)
tom.pd()
for i in range(3):
    sq('#FBBB01')
tom.pu()
tom.goto(-960,380)
tom.pd()
for i in range(3):
    sq('white')
tom.pu()
tom.goto(-960,410)
tom.pd()
for i in range(5):
    sq('white')
tom.pu()
tom.goto(-960,440)
tom.pd()
for i in range(2):
    sq('white')
tom.pu()
tom.goto(-450,230)
tom.pd()
for i in range(3):
    sq('white')
tom.pu()
tom.goto(-510,260)
tom.pd()
for i in range(6):
    sq('white')
tom.pu()
tom.goto(-540,290)
tom.pd()
sq('white')
tom.pu()
tom.goto(-480,290)
tom.pd()
for i in range(5):
    sq('white')
tom.pu()
tom.goto(-480,320)
tom.pd()
for i in range(5):
    sq('white')
tom.pu()
tom.goto(-480,350)
tom.pd()
sq('white')
tom.pu()
tom.goto(-480,380)
tom.pd()
sq('white')
tom.pu()
tom.goto(-480,410)
tom.pd()
sq('white')
tom.pu()
tom.goto(-360,350)
tom.pd()
sq('white')
tom.pu()
tom.goto(-360,380)
tom.pd()
sq('white')
tom.pu()
tom.goto(-360,410)
tom.pd()
sq('white')

tom.pu()
tom.goto(-620,-300)
tom.pd()
lay()
tom.pu()
tom.goto(-620,-270)
tom.pd()
lay()
tom.pu()
tom.goto(-620,-240)
tom.pd()
lay()
tom.pu()
tom.goto(-620,-210)
tom.pd()
lay()
tom.pu()
tom.goto(-620,-180)
tom.pd()
lay()
tom.pu()
tom.goto(-620,-150)
tom.pd()
lay()
tom.pu()
tom.goto(-650,-120)
tom.pd()
bl()
tom.pu()
tom.goto(-650,-90)
tom.pd()
bl()
tom.pu()
tom.goto(660,380)
tom.pd()
sun()
tom.pu()
tom.goto(660,380)
tom.pd()

def get_mouse_click_coor(x, y):
    print(x, y)
onscreenclick(get_mouse_click_coor)
mainloop()
onscreenclick(get_mouse_click_coor)
done()
window.tracer(True)
exitonclick()